### ISSUE TITLE
Frontpage can scroll "right/left"

### ISSUE THREAD

**Issue by CBE-RELEWISE** [Relewise/relewise-demos-shop-vue#51]
### Description of issue
I can "scroll" the front page a little bit "right/left" which gives a bit of a "messy" impression. 

### Expected result
No left/right scrolling - expected adaption to screen width.

```
Path:      /
Browser:   Edge 131.0.0.0 on Mac OS 10.15.7
Viewport:  1720 x 918 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-46--relewise-demo-shop.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Edge&browser_version=131.0&resolution=1720x918&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #46](https://deploy-preview-46--relewise-demo-shop.netlify.app/)

**Comment by mzanoni** [comment]
Fixed
